# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/
theme: jekyll-theme-simple-texture

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: Simple Texture
description: "A gem-based responsive simple texture styled Jekyll theme."
keywords: 'jekyll,theme,gem-based,blog'
author:
  name:
  job_title:
  location:
  email:
  social_links:
    - name: facebook
      url:
    - name: github
      url: https://github.com/yizeng/jekyll-theme-simple-texture
    - name: instagram
      url:
    - name: linkedin
      url:
    - name: stackoverflow
      url:
    - name: twitter
      url: 
    - name: vk
      url:
home:
  section1: <h1>Simple Texutre</h1>
  section2: <h2>A gem-based responsive simple texture styled Jekyll theme</h2>
  section3: <div class="social-links"><a class="ico-github btn" href="https://github.com/yizeng/jekyll-theme-simple-texture" title="View on GitHub"></a></div>
blog:
  cc_license: # A link to CC License of your choice, e.g. http://creativecommons.org/licenses/by-sa/4.0/.
  cc_license_image: # An image of your CC License, e.g. /assets/images/theme/cc-by-sa.png
  footer_content: A gem-based responsive simple texture styled Jekyll theme.

disqus:
  shortname:
  public_key:
google_analytics:
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
